# Generated by Django 2.1.7 on 2020-06-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0007_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'Повідомлення'},
        ),
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name_plural': 'Заявники'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'Практика'},
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('1', 'Робота'), ('2', 'Випробування'), ('3', 'Стажування')], max_length=10),
        ),
    ]
